// subprojects/vue-ts/src/components/Contador.vue
<template>
  <div>
    <h1>Contador</h1>
    <h2>{{ valor }}</h2>
    <button @click="setValor(-1)">
      Decrementar
    </button>
    <button @click="setValor(1)">
      Incrementar
    </button>
  </div>
</template>

<script lang="ts">
  import Vue from 'vue';
  export default Vue.extend({
    name: 'AppContador',
    props: {
      valorInicial: {
        type: Number,
        default: 0,
      }
    },
    data: () => ({
      valor: 0,
    }),
    mounted() {
        this.valor = this.valorInicial;
    },
    methods: {
      setValor(delta: number): void {
        this.valor += delta;
      }
    },
  })
</script>

<style>

</style>

// subprojects/react-ts/src/components/Contador.tsx
import React, { Component } from 'react';
import ContadorValor from './ContadorValor';
import logRender from '../decorators/logRender';

interface IContadorProps {
  valorInicial?: number
}

interface IContadorState {
  valor: number
}

@logRender
export default class Contador extends Component<IContadorProps, IContadorState> {
  public state = { valor: this.props.valorInicial || 0 }

  private setValor = (delta: number) => {
    this.setState({
      valor: this.state.valor + delta
    })
  }

  render(): React.ReactNode {
    return (
      <div>
        <ContadorValor contador={this.state.valor} />
        <button onClick={() => this.setValor(-10)}>-</button>
        <button onClick={() => this.setValor(10)}>+</button>
      </div>
    )
  }
}
